package entity;

import javax.persistence.*;
import java.util.Arrays;

/**
 * Generated by sarlirik on 23/09/17.
 */
@Entity
@Table(name = "productlines", schema = "classicmodels", catalog = "")
public class ProductLine {
    private String productLine;
    private String textDescription;
    private String htmlDescription;
    private byte[] image;

    @Id
    @Column(name = "productLine", nullable = false, length = 50)
    public String getProductLine() {
        return productLine;
    }

    public void setProductLine(String productLine) {
        this.productLine = productLine;
    }

    @Basic
    @Column(name = "textDescription", nullable = true, length = 4000)
    public String getTextDescription() {
        return textDescription;
    }

    public void setTextDescription(String textDescription) {
        this.textDescription = textDescription;
    }

    @Basic
    @Column(name = "htmlDescription", nullable = true, length = 16777215)
    public String getHtmlDescription() {
        return htmlDescription;
    }

    public void setHtmlDescription(String htmlDescription) {
        this.htmlDescription = htmlDescription;
    }

    @Basic
    @Column(name = "image", nullable = true)
    public byte[] getImage() {
        return image;
    }

    public void setImage(byte[] image) {
        this.image = image;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        ProductLine that = (ProductLine) o;

        if (productLine != null ? !productLine.equals(that.productLine) : that.productLine != null) return false;
        if (textDescription != null ? !textDescription.equals(that.textDescription) : that.textDescription != null)
            return false;
        if (htmlDescription != null ? !htmlDescription.equals(that.htmlDescription) : that.htmlDescription != null)
            return false;
        if (!Arrays.equals(image, that.image)) return false;

        return true;
    }

    @Override
    public int hashCode() {
        int result = productLine != null ? productLine.hashCode() : 0;
        result = 31 * result + (textDescription != null ? textDescription.hashCode() : 0);
        result = 31 * result + (htmlDescription != null ? htmlDescription.hashCode() : 0);
        result = 31 * result + Arrays.hashCode(image);
        return result;
    }
}
